org: garrybamrah
app: youtube-tutorial
service: youtube-tutorial
frameworkVersion: '2 || 3'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: '20201221'

functions:
  hello:
    handler: ./src/Employee/handler.hello
    events:
      - httpApi:
          path: /employee
          method: get
plugins:
  - serverless-offline
  - serverless-plugin-typescript
custom:
  serverless-offline:
    httpPort: 9000